data_path: d:/jo77pihe/Registered
source_folder: 20220203_AutoQuant_NotAveraged/Train_data/Raw
target_folder: 20220203_AutoQuant_NotAveraged/Train_data/Deconved
test_folder: D:/jo77pihe/Registered/Deconved_AutoQuant_R2/Test_Raw
result_path: ./CARE_100
psf: C:/Users/Johan/Documents/FAU_Masterarbeit/Implementation/Data/PSF
train: True
z_shape: 16
xy_shape: 16
n_patches: 1
data_augmented_path: ./Registered/Data_npz
validation_split: 0.1
epochs: 2
batch_size: 1
learning_rate: 0.001